# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Musing < Formula
  desc "CLI for managing multi-service development stacks"
  homepage "https://github.com/stevengregory/musing-cli"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevengregory/musing-cli/releases/download/v0.8.3/musing-cli_0.8.3_darwin_amd64.tar.gz"
      sha256 "c1ece86270cc3bcbd382d35188dc4a0fb271a7c30fa7fe8082f5fe4da24627a3"

      define_method(:install) do
        bin.install "musing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevengregory/musing-cli/releases/download/v0.8.3/musing-cli_0.8.3_darwin_arm64.tar.gz"
      sha256 "517e89fd7948ff7238d0dc20c8d02b753b53a4d80077d02782fd3d5c7882e49a"

      define_method(:install) do
        bin.install "musing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevengregory/musing-cli/releases/download/v0.8.3/musing-cli_0.8.3_linux_amd64.tar.gz"
      sha256 "78b9f26c398115a17273e2cb7161e6ca7b1ae984619367558a65da8769ee9604"
      define_method(:install) do
        bin.install "musing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevengregory/musing-cli/releases/download/v0.8.3/musing-cli_0.8.3_linux_arm64.tar.gz"
      sha256 "e86fbcdd69509f0951af7895cd1236f8bbb1792fd80608ce6d57834b9f59f605"
      define_method(:install) do
        bin.install "musing"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/musing --version")
  end
end
